name: Auto Sync Fork

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite execução manual

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout o repositório fork
      - name: Checkout Fork
        uses: actions/checkout@v3

      # Adicionar o repositório original como upstream
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/Ana-Teste/reactTeste.git
          git fetch upstream

      # Mesclar as alterações do repositório original no fork
      - name: Merge Changes
        run: |
          git checkout main
          git pull upstream main --no-commit --no-ff
          git push origin main
