name: Auto Sync Fork

on:
  schedule:
    - cron: '*/15 * * * *' # Executa a cada 15 minutos
  workflow_dispatch: # Permite execução manual

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout o repositório fork
      - name: Checkout Fork
        uses: actions/checkout@v3

      # Configurar o repositório original como 'upstream'
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/Ana-Teste/reactTeste.git
          git fetch upstream

      # Mesclar mudanças do repositório original (upstream/main) no fork
      - name: Merge Changes
        run: |
          git pull upstream main --no-commit --no-ff
          git push origin main
