name: Sync Repository

# Gatilhos: sincroniza quando há push no repositório original ou manualmente
on:
  push:
    branches:
      - main # Substitua 'main' pelo nome da branch principal do repositório original, se for diferente
  workflow_dispatch: # Permite executar manualmente, se necessário

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Verificar o código do fork
      - name: Checkout Fork
        uses: actions/checkout@v3

      # Adicionar o repositório original como upstream
      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/Ana-Teste/reactTeste.git
          git fetch upstream

      # Mesclar alterações do repositório original, ignorando a pasta 'public'
      - name: Merge Changes and Ignore 'public'
        run: |
          git pull upstream main --no-commit --no-ff
          rm -rf public # Remove a pasta public antes de confirmar
          git add .
          git commit -m "Sync with upstream, ignoring public"
          git push origin main
